#!/bin/bash

echo "🚀 足球聯賽系統部署腳本"
echo "=================================="
echo ""
echo "✅ 本地構建成功！"
echo "✅ 代碼已推送到 GitHub"
echo ""
echo "🔄 Vercel 正在自動部署..."
echo ""
echo "📋 部署資訊："
echo "   - GitHub 倉庫: https://github.com/clawdfelix-ship-it/football-league-system"
echo "   - Vercel 專案: https://vercel.com/clawdfelix-ship-it/football-league-system"
echo "   - 預計網址: https://football-league-system.vercel.app"
echo ""
echo "⏱️  部署通常需要 2-3 分鐘完成"
echo ""
echo "🔍 您可以："
echo "   1. 訪問 Vercel 控制台查看部署狀態"
echo "   2. 等待幾分鐘後訪問網址"
echo "   3. 使用 'npm run dev' 在本地測試"
echo ""
echo "💡 登入資訊："
echo "   - 管理員: admin@football.com / password"
echo "   - 用戶: user@football.com / password"
echo ""
echo "✨ 部署完成後，您的足球聯賽系統將上線！"